### ISSUE TITLE
Docker stack fails

### ISSUE THREAD

**Issue by justinbyerss** [chirpstack/chirpstack-docker#88] opened 2023-07-20 04:18 UTC
Hi,

I have tried to run the Chirpstack using the supplied docker-compose.yml and I am getting the following errors

ERROR: for mosquitto  Cannot start service mosquitto: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/compose/configuration/mosquitto/mosquitto.conf" to rootfs at "/mosquitto/config/mosquitto.conf": mount /compose/configuration/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by timmills** [comment] 2023-07-25 22:29
This will happen if the repo isnt cloned first

**Comment by remyar** [comment] 2023-09-15 19:14
i have the same problem

**Comment by brocaar** [comment] 2023-09-19 09:35
@remyar please see the comment from @timmills, does this solve your issue? if not, please provide step by step instructions to reproduce the issue.

**Comment by plaes** [comment] 2023-10-11 08:28
Apparently one needs to run `make import-lorawan-devices` in current directory to populate one of the required directories for mqtt container setup.

**Comment by brocaar** [comment] 2023-10-11 08:42
The above is not true, there is no need to run `make import-lorawan-devices`.

Please see this documentation: https://www.chirpstack.io/docs/getting-started/docker.html. With the documented steps, I'm not able to reproduce this issue. As there hasn't been any feedback with reproducible steps I'm closing this issue.

**Closed by brocaar** 2023-10-11 08:42 UTC
